markdown: kramdown
kramdown:
  input: GFM
  use_coderay: true

# Gems
gems: [
  "jekyll-paginate",
  "jekyll/scholar"
]

# setting for jekyll-paginate
paginate: 5

# setting for jekyll-scholar
scholar:
  style: apa

# exclude files
exclude: ["README.md"]